language: objective-c
osx_image: xcode7.3
env:
  matrix:
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=8.0"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=10.1"
xcode_workspace: NCMBTests/NCMBTests.xcworkspace
xcode_scheme: NCMBTests
xcode_sdk: iphonesimulator
before_install:
  - gem install xcpretty
  - cd NCMBTests
  - pod install
before_script:
  - set -o pipefail
script:
  - xcodebuild -workspace NCMBTests.xcworkspace -scheme NCMBTests -destination "${TEST_OS}" -sdk iphonesimulator test | xcpretty -c
